 name: pyart
 channels:
   - conda-forge
 dependencies:
   - python>=3.6,<3.8
   - numpy
   - matplotlib
   - cartopy
   - rasterio
   - jupyter
   - metpy
   - siphon
   - pandas
   - pip
   - xarray
   - ipywidgets
   - boto3
   - botocore
   - s3fs
   - seaborn
   - scikit-image
   - arm_pyart

