# Basic environment for Py-ART.
# includes s3fs for AWS downloads and spyder for editing
name: pyart_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - wradlib
  - cartopy
  - arm_pyart
  - xarray
  - s3fs
  - spyder